### ISSUE TITLE
Add link to this repo on AMO

### ISSUE THREAD

**Issue by Gitoffthelawn** [oyenamit/fat-free-firefox#2]
Thank you for this excellent extension.

You may want to add this repo to the AMO page for this extension as the "Add-on home page".

**Comment by oyenamit** [comment]
Thank you so much for your interest in this add-on and for this suggestion.
I have added this repo as Add-on home page in AMO.

**Comment by Gitoffthelawn** [comment]
Thank _you_ for the great extension and your hard work!
