### ISSUE TITLE
Remove broken link on AMO

### ISSUE THREAD

**Issue by Gitoffthelawn** [oyenamit/fat-free-firefox#3]
The AMO description currently contains a link to a non-existent thread on mozillazine.  You may desire to remove it.

**Comment by oyenamit** [comment]
Thanks for pointing this out. The link is actually valid (http://forums.mozillazine.org/viewtopic.php?f=48&t=2958299) but somehow AMO is messing up the ampersand. I have removed the link anyway.

**Comment by Gitoffthelawn** [comment]
Sounds good!
