### ISSUE TITLE
Firefox Quantum alternatives

### ISSUE THREAD

**Issue by saintsal** [oyenamit/fat-free-firefox#6]
Thanks for making such a great extension - I've been a long-time user.  It's a shame that Mozilla no longer supports this, especially since they're quite a pro-privacy organization.

I'm wondering:

1. Which features are no longer supported, and is it possible to continue with the remaining features or convert blocking/disabling to notification?  That would still be useful for defending privacy.
2. What are you going to use personally now?  Are you sticking with Firefox?  Do you use or recommend any other privacy extensions?

Thanks again.  Your work on this has helped me live free!

**Comment by oyenamit** [comment]
@saintsal Thank you so much for supporting this add-on.

1. WebExtensions API does not support changing *about:config* entries. Out of 11 features in Fat-Free Fox, 10 depend on manipulating about:config settings. That is why this add-on will not work in Quantum. Displaying notifications when, for example, Firefox makes speculative connections would mean parsing the network traffic. That requires a whole different approach, a feasibility study under WebExtensions and would probably be a completely new project.

2. Currently, I only have NoScript and uBlock Origin. I believe one can use the Privacy and Security settings provided by [ghacks.net](https://www.ghacks.net/2015/08/18/a-comprehensive-list-of-firefox-privacy-and-security-settings/) but I feel that approach is very cumbersome to track and manage.
